// Fotos de cada bichinho, pra abrir em álbum na aba "Bebês".
// Pra adicionar mais fotos de um bicho, é só colar o caminho da imagem
// na lista dele (a primeira imagem de cada uma já é usada como capinha
// no card principal).
const BICHINHOS_GALERIA = {
  maia: {
    nome: "Maia",
    capa: "img/bichinhos/maia.jpg",
    fotos: [
      "img/bichinhos/maia-1.jpg",
      "img/bichinhos/maia-2.jpg",
      "img/bichinhos/maia-3.jpg",
      "img/bichinhos/maia-4.jpg",
      "img/bichinhos/maia-5.jpg",
      "img/bichinhos/maia-6.jpg",
      "img/bichinhos/maia-7.jpg",
      "img/bichinhos/maia-8.jpg",
      "img/bichinhos/maia-9.jpg",
      "img/bichinhos/maia-10.jpg",
      "img/bichinhos/maia-11.jpg",
      "img/bichinhos/maia-12.jpg",
    ],
  },
  ellie: {
    nome: "Ellie",
    capa: "img/bichinhos/ellie.jpg",
    fotos: [
      "img/bichinhos/ellie-1.jpg",
      "img/bichinhos/ellie-2.jpg",
      "img/bichinhos/ellie-3.jpg",
      "img/bichinhos/ellie-4.jpg",
      "img/bichinhos/ellie-5.jpg",
      "img/bichinhos/ellie-6.jpg",
      "img/bichinhos/ellie-7.jpg",
      "img/bichinhos/ellie-8.jpg",
    ],
  },
  negao: {
    nome: "Negão",
    capa: "img/bichinhos/negao.jpg",
    fotos: [
      "img/bichinhos/negao-1.jpg",
      "img/bichinhos/negao-2.jpg",
      "img/bichinhos/negao-3.jpg",
      "img/bichinhos/negao-4.jpg",
      "img/bichinhos/negao-5.jpg",
      "img/bichinhos/negao-6.jpg",
      "img/bichinhos/negao-7.jpg",
      "img/bichinhos/negao-8.jpg",
      "img/bichinhos/negao-9.jpg",
    ],
  },
  pingo: {
    nome: "Pingo",
    capa: "img/bichinhos/pingo.jpg",
    fotos: [
      "img/bichinhos/pingo-1.jpg",
      "img/bichinhos/pingo-2.jpg",
      "img/bichinhos/pingo-3.jpg",
      "img/bichinhos/pingo-4.jpg",
      "img/bichinhos/pingo-5.jpg",
      "img/bichinhos/pingo-6.jpg",
      "img/bichinhos/pingo-7.jpg",
      "img/bichinhos/pingo-8.jpg",
      "img/bichinhos/pingo-9.jpg",
    ],
  },
  josh: {
    nome: "Josh",
    capa: "img/bichinhos/josh.jpg",
    fotos: [
      "img/bichinhos/josh-1.jpg",
      "img/bichinhos/josh-2.jpg",
      "img/bichinhos/josh-3.jpg",
      "img/bichinhos/josh-4.jpg",
      "img/bichinhos/josh-5.jpg",
      "img/bichinhos/josh-6.jpg",
      "img/bichinhos/josh-7.jpg",
    ],
  },
  vitoria: {
    nome: "Vitória",
    capa: "img/bichinhos/vitoria.jpg",
    fotos: [
      "img/bichinhos/vitoria-1.jpg",
      "img/bichinhos/vitoria-2.jpg",
      "img/bichinhos/vitoria-3.jpg",
      "img/bichinhos/vitoria-4.jpg",
      "img/bichinhos/vitoria-5.jpg",
      "img/bichinhos/vitoria-6.jpg",
      "img/bichinhos/vitoria-7.jpg",
      "img/bichinhos/vitoria-8.jpg",
      "img/bichinhos/vitoria-9.jpg",
    ],
  },
  sansara: {
    nome: "Samsara",
    capa: "img/bichinhos/sansara.jpg",
    fotos: [
      "img/bichinhos/sansara-1.jpg",
      "img/bichinhos/sansara-2.jpg",
      "img/bichinhos/sansara-3.jpg",
      "img/bichinhos/sansara-4.jpg",
      "img/bichinhos/sansara-5.jpg",
      "img/bichinhos/sansara-6.jpg",
      "img/bichinhos/sansara-7.jpg",
    ],
  },
  hadox: {
    nome: "Hadox",
    capa: "img/bichinhos/hadox.jpg",
    fotos: [
      "img/bichinhos/hadox-1.jpg",
      "img/bichinhos/hadox-2.jpg",
      "img/bichinhos/hadox-3.jpg",
      "img/bichinhos/hadox-4.jpg",
      "img/bichinhos/hadox-5.jpg",
      "img/bichinhos/hadox-6.jpg",
      "img/bichinhos/hadox-7.jpg",
    ],
  },
  pichula: {
    nome: "Pichula",
    capa: "img/bichinhos/pichula.jpg",
    fotos: [
      "img/bichinhos/pichula-1.jpg",
      "img/bichinhos/pichula-2.jpg",
      "img/bichinhos/pichula-3.jpg",
      "img/bichinhos/pichula-4.jpg",
      "img/bichinhos/pichula-5.jpg",
      "img/bichinhos/pichula-6.jpg",
      "img/bichinhos/pichula-7.jpg",
    ],
  },
};
